version: '3.8'
services:
  postgres:
    image: postgres:15.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animeland
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
